package fr.gocraft.apt;

/// Writes the tree back out as the builder calls an author could have written.
///
/// That is the point of §07's fan-in: the annotation facade is not a second way
/// of describing a command, it is a shorthand for the first one. Emitting
/// builder calls rather than a serialized tree means the annotations inherit
/// every rule the builder enforces — and that a conformance test comparing the
/// two is comparing a thing to itself, which is exactly what it should find.
final class Emitter {

    private final StringBuilder out = new StringBuilder();

    String render(String packageName, String generated, String target, Tree root) {
        if (!packageName.isEmpty()) {
            line(0, "package " + packageName + ";");
            blank();
        }
        line(0, "import fr.gocraft.api.command.ArgType;");
        line(0, "import fr.gocraft.api.command.Command;");
        line(0, "import fr.gocraft.api.command.CommandSet;");
        blank();
        line(0, "// Code generated by gocraft-apt. DO NOT EDIT.");
        line(0, "//");
        line(0, "// Source: " + target + ", from its @Cmd and @Sub annotations.");
        line(0, "public final class " + generated + " {");
        blank();
        line(1, "private " + generated + "() {");
        line(1, "}");
        blank();
        line(1, "/// The commands " + target + " declares, bound to one instance of it.");
        line(1, "public static CommandSet of(" + target + " target) {");
        line(2, "return Command.tree(");
        node(3, root, true);
        line(2, ");");
        line(1, "}");
        line(0, "}");
        return out.toString();
    }

    private void node(int depth, Tree tree, boolean last) {
        String head = tree.argument
                ? "Command.arg(\"" + tree.name + "\", " + tree.type + ")"
                : "Command.literal(\"" + tree.name + "\")";
        line(depth, head);
        if (!tree.permission.isEmpty()) {
            line(depth + 1, ".permission(\"" + tree.permission + "\")");
        }
        if (tree.invoke != null) {
            line(depth + 1, ".executes(context -> " + tree.invoke + ")");
        }
        int remaining = tree.children.size();
        for (Tree child : tree.children.values()) {
            remaining--;
            line(depth + 1, ".then(");
            node(depth + 2, child, true);
            line(depth + 1, remaining == 0 ? ")" : ")");
        }
        if (!last) {
            append(",");
        }
    }

    private void line(int depth, String text) {
        out.append("    ".repeat(depth)).append(text).append('\n');
    }

    private void append(String text) {
        out.setLength(out.length() - 1);
        out.append(text).append('\n');
    }

    private void blank() {
        out.append('\n');
    }
}
