package fr.gocraft.apt;

import fr.gocraft.api.PluginEvent;

import java.util.List;

/// Writes the codec for one [fr.gocraft.api.PluginEvent] class.
///
/// It reads through the accessors rather than the fields, because the fields
/// are the author's and are usually private — and reaching past them with
/// reflection would trade a compile error for a runtime one, on a path the tick
/// is waiting on.
final class EventEmitter extends ValueEmitter {

    String render(String qualified, PluginEvent declared, List<EventProcessor.Field> layout) {
        int lastDot = qualified.lastIndexOf('.');
        String packageName = lastDot < 0 ? "" : qualified.substring(0, lastDot);
        String simple = lastDot < 0 ? qualified : qualified.substring(lastDot + 1);
        String generated = simple + "Layout";

        if (!packageName.isEmpty()) {
            line(0, "package " + packageName + ";");
            blank();
        }
        line(0, "import fr.gocraft.api.CustomEvent;");
        line(0, "import fr.gocraft.api.EffectSink;");
        line(0, "import fr.gocraft.api.Value;");
        line(0, "import java.util.List;");
        blank();
        line(0, "// Code generated by gocraft-apt. DO NOT EDIT.");
        line(0, "//");
        line(0, "// Source: " + simple + ", from its @PluginEvent annotation.");
        line(0, "//");
        line(0, "// Field order is the wire contract. Appending one is safe; reordering or");
        line(0, "// removing one shifts every index for everyone already compiled against");
        line(0, "// this event.");
        line(0, "public final class " + generated + " implements CustomEvent {");
        blank();
        line(1, "@Override");
        line(1, "public String eventType() {");
        line(2, "return \"" + declared.value() + "\";");
        line(1, "}");
        blank();

        line(1, "@Override");
        line(1, "public boolean cancellable() {");
        line(2, "return " + declared.cancellable() + ";");
        line(1, "}");
        blank();

        writeFields(simple, layout);
        blank();
        writeSetFields(simple, layout);
        blank();
        writeCreate(simple, declared, layout);

        if (carriesAPlayer(layout)) {
            writePlayerHelper();
        }
        line(0, "}");
        return out.toString();
    }

    private void writeFields(String simple, List<EventProcessor.Field> layout) {
        line(1, "@Override");
        line(1, "public List<Value> fields(Object event) {");
        if (layout.isEmpty()) {
            line(2, "return List.of();");
            line(1, "}");
            return;
        }
        line(2, simple + " target = (" + simple + ") event;");
        List<String> expressions = new java.util.ArrayList<>(layout.size());
        for (EventProcessor.Field field : layout) {
            expressions.add(encodeField(2, field, "target." + field.name() + "()"));
        }
        line(2, "return List.of(");
        for (int index = 0; index < expressions.size(); index++) {
            line(3, expressions.get(index) + (index + 1 == expressions.size() ? "" : ","));
        }
        line(2, ");");
        line(1, "}");
    }

    private void writeSetFields(String simple, List<EventProcessor.Field> layout) {
        line(1, "@Override");
        line(1, "public void setFields(Object event, List<Value> fields) {");
        if (!hasMutable(layout)) {
            // Nothing may be written, so the host refused every mutation before
            // this was called. Saying so beats an empty body someone reads as
            // an oversight.
            line(2, layout.isEmpty()
                    ? "// This event carries nothing, so there is nothing to write back."
                    : "// Every field is final: this event is read-only to subscribers.");
            line(1, "}");
            return;
        }
        line(2, simple + " target = (" + simple + ") event;");
        for (int index = 0; index < layout.size(); index++) {
            EventProcessor.Field field = layout.get(index);
            if (!field.mutable()) {
                continue;
            }
            // Each write stands alone: one field arriving in a shape this build
            // does not read must not lose the others, since the host applied
            // them all and the emitter's object has to end up where the dispatch
            // got to.
            line(2, "try {");
            decodeValue(3, field.carried(), "fields.get(" + index + ")", field.name(),
                    "field " + index);
            line(3, "target." + field.setter() + "(" + field.name() + ");");
            line(2, "} catch (RuntimeException ignored) {");
            line(2, "}");
        }
        line(1, "}");
    }

    private void writeCreate(String simple, PluginEvent declared,
            List<EventProcessor.Field> layout) {
        // Building the event a subscriber receives. Every value is checked: a
        // kind that does not match means the two plugins compiled against
        // different versions of the layout.
        line(1, "@Override");
        line(1, "public Object create(List<Value> fields, EffectSink sink) {");
        line(2, "if (fields.size() < " + layout.size() + ") {");
        line(3, "throw new IllegalArgumentException(\"" + declared.value() + " arrived with \""
                + " + fields.size() + \" fields, its layout declares " + layout.size() + "\");");
        line(2, "}");
        for (int index = 0; index < layout.size(); index++) {
            EventProcessor.Field field = layout.get(index);
            decodeValue(2, field.carried(), "fields.get(" + index + ")", field.name(),
                    "field " + index + " of " + declared.value());
        }
        line(2, "return new " + simple + "(");
        for (int index = 0; index < layout.size(); index++) {
            line(3, layout.get(index).name() + (index + 1 == layout.size() ? "" : ","));
        }
        line(2, ");");
        line(1, "}");
    }

    private static boolean hasMutable(List<EventProcessor.Field> layout) {
        return layout.stream().anyMatch(EventProcessor.Field::mutable);
    }
}