package fr.gocraft.apt;

import fr.gocraft.api.PluginEvent;

import java.util.List;

/// Writes the codec for one [fr.gocraft.api.PluginEvent] class.
///
/// It reads through the accessors rather than the fields, because the fields
/// are the author's and are usually private — and reaching past them with
/// reflection would trade a compile error for a runtime one, on a path the tick
/// is waiting on.
///
/// Reading widens for free: an `int` fits the `long` a Value.Int carries.
/// Writing has to narrow explicitly, which is why the declared type travels
/// this far.
final class EventEmitter {

    private final StringBuilder out = new StringBuilder();

    String render(String qualified, PluginEvent declared, List<EventProcessor.Field> layout) {
        int lastDot = qualified.lastIndexOf('.');
        String packageName = lastDot < 0 ? "" : qualified.substring(0, lastDot);
        String simple = lastDot < 0 ? qualified : qualified.substring(lastDot + 1);
        String generated = simple + "Layout";

        if (!packageName.isEmpty()) {
            line(0, "package " + packageName + ";");
            blank();
        }
        line(0, "import fr.gocraft.api.EventLayout;");
        line(0, "import fr.gocraft.api.Value;");
        line(0, "import java.util.List;");
        blank();
        line(0, "// Code generated by gocraft-apt. DO NOT EDIT.");
        line(0, "//");
        line(0, "// Source: " + simple + ", from its @PluginEvent annotation.");
        line(0, "//");
        line(0, "// Field order is the wire contract. Appending one is safe; reordering or");
        line(0, "// removing one shifts every index for everyone already compiled against");
        line(0, "// this event.");
        line(0, "public final class " + generated + " implements EventLayout {");
        blank();
        line(1, "@Override");
        line(1, "public String eventType() {");
        line(2, "return \"" + declared.value() + "\";");
        line(1, "}");
        blank();

        line(1, "@Override");
        line(1, "public List<Value> fields(Object event) {");
        if (layout.isEmpty()) {
            line(2, "return List.of();");
        } else {
            line(2, simple + " target = (" + simple + ") event;");
            line(2, "return List.of(");
            for (int index = 0; index < layout.size(); index++) {
                EventProcessor.Field field = layout.get(index);
                String comma = index == layout.size() - 1 ? "" : ",";
                line(3, "new Value." + field.kind().record + "(target." + field.name() + "())"
                        + comma);
            }
            line(2, ");");
        }
        line(1, "}");
        blank();

        line(1, "@Override");
        line(1, "public void setFields(Object event, List<Value> fields) {");
        if (!hasMutable(layout)) {
            // Nothing may be written, so the host refused every mutation before
            // this was called. Saying so beats an empty body someone reads as
            // an oversight.
            line(2, layout.isEmpty()
                    ? "// This event carries nothing, so there is nothing to write back."
                    : "// Every field is final: this event is read-only to subscribers.");
        } else {
            line(2, simple + " target = (" + simple + ") event;");
            for (int index = 0; index < layout.size(); index++) {
                EventProcessor.Field field = layout.get(index);
                if (!field.mutable()) {
                    continue;
                }
                line(2, "if (fields.get(" + index + ") instanceof Value." + field.kind().record
                        + "(" + carried(field) + " " + field.name() + ")) {");
                line(3, "target." + field.setter() + "(" + narrow(field) + ");");
                line(2, "}");
            }
        }
        line(1, "}");
        line(0, "}");
        return out.toString();
    }

    /// The type the Value record hands back, which is not always the field's.
    private String carried(EventProcessor.Field field) {
        return switch (field.kind()) {
            case BOOL -> "boolean";
            case INT -> "long";
            case DECIMAL -> "double";
            case TEXT -> "String";
            case BYTES -> "byte[]";
        };
    }

    private String narrow(EventProcessor.Field field) {
        if (field.kind().narrows() && !field.declared().equals(carried(field))) {
            return "(" + field.declared() + ") " + field.name();
        }
        return field.name();
    }

    private static boolean hasMutable(List<EventProcessor.Field> layout) {
        return layout.stream().anyMatch(EventProcessor.Field::mutable);
    }

    private void line(int depth, String text) {
        out.append("    ".repeat(depth)).append(text).append('\n');
    }

    private void blank() {
        out.append('\n');
    }
}