package fr.gocraft.apt;

import java.util.List;

/// Writes the codec for one [fr.gocraft.api.EventValue] class.
///
/// A record is an event's payload one level down, so this writes the same two
/// directions an event codec does and by the same rules. It is a pair of static
/// methods rather than an interface implementation: nothing looks a record codec
/// up by name at runtime — the event codec that carries it calls it directly,
/// and both are generated into the same package in the same javac round.
///
/// No setFields. A subscriber changes a record by having the whole thing handed
/// back to it in a mutation, and the host applies mutations by path against the
/// values rather than against anybody's object. What is written back into an
/// author's object is the event's own fields, one level up.
final class RecordEmitter extends ValueEmitter {

    String render(String qualified, List<EventProcessor.Field> layout) {
        int lastDot = qualified.lastIndexOf('.');
        String packageName = lastDot < 0 ? "" : qualified.substring(0, lastDot);
        String simple = lastDot < 0 ? qualified : qualified.substring(lastDot + 1);
        String generated = simple + "Values";

        if (!packageName.isEmpty()) {
            line(0, "package " + packageName + ";");
            blank();
        }
        line(0, "import fr.gocraft.api.EffectSink;");
        line(0, "import fr.gocraft.api.Value;");
        line(0, "import java.util.List;");
        blank();
        line(0, "// Code generated by gocraft-apt. DO NOT EDIT.");
        line(0, "//");
        line(0, "// Source: " + simple + ", from its @EventValue annotation.");
        line(0, "//");
        line(0, "// Field order is the wire contract, exactly as it is for an event: this");
        line(0, "// record travels as a list, and its declaration order is that list's");
        line(0, "// order.");
        line(0, "public final class " + generated + " {");
        blank();
        line(1, "private " + generated + "() {");
        line(1, "}");
        blank();

        line(1, "static Value encode(" + simple + " value) {");
        if (layout.isEmpty()) {
            line(2, "return new Value.List(List.of());");
        } else {
            List<String> expressions = new java.util.ArrayList<>(layout.size());
            for (EventProcessor.Field field : layout) {
                expressions.add(encodeField(2, field, "value." + field.name() + "()"));
            }
            line(2, "return new Value.List(List.of(");
            for (int index = 0; index < expressions.size(); index++) {
                line(3, expressions.get(index) + (index + 1 == expressions.size() ? "" : ","));
            }
            line(2, "));");
        }
        line(1, "}");
        blank();

        line(1, "static " + simple + " decode(Value value, EffectSink sink) {");
        line(2, "if (!(value instanceof Value.List(List<Value> fields))) {");
        line(3, "throw new IllegalArgumentException(\"" + simple + " is not a list\");");
        line(2, "}");
        line(2, "if (fields.size() < " + layout.size() + ") {");
        line(3, "throw new IllegalArgumentException(\"" + simple + " arrived with \""
                + " + fields.size() + \" fields, its layout declares " + layout.size() + "\");");
        line(2, "}");
        for (int index = 0; index < layout.size(); index++) {
            EventProcessor.Field field = layout.get(index);
            decodeValue(2, field.carried(), "fields.get(" + index + ")", field.name(),
                    "field " + index + " of " + simple);
        }
        line(2, "return new " + simple + "(");
        for (int index = 0; index < layout.size(); index++) {
            line(3, layout.get(index).name() + (index + 1 == layout.size() ? "" : ","));
        }
        line(2, ");");
        line(1, "}");

        if (carriesAPlayer(layout)) {
            writePlayerHelper();
        }
        line(0, "}");
        return out.toString();
    }
}